### ISSUE TITLE
Breaks redmine API

### ISSUE THREAD

**Issue by lmorillas** [commandprompt/redmine_canned_responses#21]
```
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.10.4
  Mercurial                      4.8.2
  Bazaar                         2.8.0
  Git                            2.20.1
  Filesystem                     
Redmine plugins:
  redmine_tags                   4.0.0
  redmine_canned_responses       0.3.2
```
When redmine_canned_respnoses is installed,  curl `<server>/projects.json` raises an error:

```
App 17103 output: I, [2020-09-13T06:32:07.833207 #17103]  INFO -- : Started GET "/projects.json" for 83.38.157.49 at 2020-09-13 06:32:07 +0000
App 17103 output: I, [2020-09-13T06:32:07.834043 #17103]  INFO -- : Processing by ProjectsController#index as JSON
App 17103 output: I, [2020-09-13T06:32:07.838023 #17103]  INFO -- :   Current user: admin (id=1)
App 17103 output: I, [2020-09-13T06:32:07.843417 #17103]  INFO -- :   Rendering projects/index.api.rsb
App 17103 output: I, [2020-09-13T06:32:07.891674 #17103]  INFO -- :   Rendered projects/index.api.rsb (48.2ms)
App 17103 output: I, [2020-09-13T06:32:07.891811 #17103]  INFO -- : Completed 500 Internal Server Error in 58ms (ActiveRecord: 3.1ms)
App 17103 output: F, [2020-09-13T06:32:07.892863 #17103] FATAL -- :   
App 17103 output: F, [2020-09-13T06:32:07.892889 #17103] FATAL -- : ActionView::Template::Error (undefined method `render_api_redmine_tags' for #<#<Class:0x0000562b03b22238>:0x0000562b032142e0>
App 17103 output: Did you mean?  render_api_includes):
App 17103 output: F, [2020-09-13T06:32:07.892943 #17103] FATAL -- :     13:       render_api_custom_values project.visible_custom_field_values, api
App 17103 output:     14:       render_api_includes(project, api)
App 17103 output:     15: 
App 17103 output:     16:       api.created_on  project.created_on
App 17103 output:     17:       api.updated_on  project.updated_on
App 17103 output:     18:     end
App 17103 output:     19:   end
App 17103 output: F, [2020-09-13T06:32:07.892959 #17103] FATAL -- :   
App 17103 output: F, [2020-09-13T06:32:07.892969 #17103] FATAL -- : app/views/projects/index.api.rsb:16:in `block (4 levels) in _27171045b848e14f069ad3d26d5c29f7'
App 17103 output: lib/redmine/views/builders/structure.rb:74:in `method_missing'
App 17103 output: app/views/projects/index.api.rsb:3:in `block (3 levels) in _27171045b848e14f069ad3d26d5c29f7'
App 17103 output: app/views/projects/index.api.rsb:2:in `each'
App 17103 output: app/views/projects/index.api.rsb:2:in `block (2 levels) in _27171045b848e14f069ad3d26d5c29f7'
App 17103 output: lib/redmine/views/builders/structure.rb:35:in `array'
App 17103 output: app/views/projects/index.api.rsb:1:in `block in _27171045b848e14f069ad3d26d5c29f7'
App 17103 output: lib/redmine/views/builders.rb:36:in `for'
App 17103 output: app/views/projects/index.api.rsb:1:in `_27171045b848e14f069ad3d26d5c29f7'

```

**Comment by eug3nix** [comment]
Hi. Judging by the backtrace, request crashes in redmine_tags plugin.
I assume you have this one installed ? https://github.com/ixti/redmine_tags
I have tried to replicate this bug on my Remine 4.1 instance but redmine_tags fails to load due to use of deprecated alias_method_chain API so I was unable to replicate the issue.
Also this tags plugin is marked as EOL now.
As for v4 support for the canned responses plugin - I will be publishing an updated v4 compatible version soon.
Cheers!

**Comment by lmorillas** [comment]
Yes, you must replace the  alias_method_chain by 2  alias_method at https://github.com/ixti/redmine_tags/blob/1c2e829485c1cb029147b123a93bcee5b9bc81e0/lib/redmine_tags/patches/api_template_handler_patch.rb#L8 for installing it with rails 5.2

I deleted the project endpoint at your API and the rest is working fine

**Comment by eug3nix** [comment]
@lmorillas please take a look at 4.0 branch of this plugin. I've tested it locally against Redmine v4.1 installation.
